### ISSUE TITLE
State

### ISSUE THREAD

**Issue by jstabenow** [dcos-labs/MongoDB#1]
Hey!
First, thanks for your work! That is exactly what I am looking for!
But is it possible you say something about your next steps if there are any? I am waiting for a DC/OS MongoDB package and it would be nice to know something about it.

**Comment by usultrared** [comment]
@jstabenow We are still test this in production env. And trying to add more HA/Replic feature.  Looking forward to having your contribution as well.  Any thoughts, feel free to let us know as well

**Comment by tobilg** [comment]
Any updates on this?

**Comment by 19h** [comment]
We'd love to deploy Mongo on DC/OS, and this is pretty important for us. Could you please outline the current known issues, so that we could at least investigate ourself?

**Comment by usultrared** [comment]
@KenanSulayman I have deployed our mongo version into customer env. Do you want to work on this and contribute code on this? We are happy to see your contribution

**Comment by usultrared** [comment]
@KenanSulayman Do you have specific requirement ?

**Comment by 19h** [comment]
The most pressing issue with containerising MongoDB for DC/OS is the need of using a host-local mount (nfs) for data storage (the specific machines have respective roles set). We should be able to completely nuke the framework and still be able to start directly from the nfs (which potentially is a historic backup). How would you describe the stability of the framework? Did you ever run into issues where data was lost or out-of-sync?

**Comment by tobilg** [comment]
@KenanSulayman How do you image the mounting of the NFS volumes should work? I guess they already need to exist on the agent nodes before launching the framework.

Probably, using [local persistent volumes](https://mesosphere.github.io/marathon/docs/persistent-volumes.html) together with only having one ReplicaSet node per agent would minimize the possible failure scenarios. Unique host constraints have to be implemented in the framework scheduler though, this is not part of the mesos.proto definitions.

**Comment by tangmingdong123** [comment]
thks for @tobilg.   We can add reservation for the framework, then the mongo node will restart on the same host before it down and reuse the same directory and data files.
